### ISSUE TITLE
Flyway 5.1.x support

### ISSUE THREAD

**Issue by YashchenkoN** [flyway/flyway-test-extensions#59]
Any plans for this?
It's needed in order to be able to execute flyway in tests which use Spring 5.1.X / Spring Boot 2.1.X

**Comment by FlorianGWE** [comment]
Plans Yes, but add the moment not many spare time to do this.

Please provide  more information, what are the problems. 
Why flyway-test-extension do not work correct with Spring Boot 2.x and Spring 5.1.

In Spring 5.1 I see not so many changes that the setup of sample for  Spring 5 will not work.

**Comment by YashchenkoN** [comment]
Spring 5.1 uses Flyway 5.1.X, but the latest version of flyway-test-extension can't work with Flyway 5.1.X because of the following error:

```
java.lang.NoSuchMethodError: org.flywaydb.core.Flyway.getLocations()[Ljava/lang/String;
	at org.flywaydb.test.FlywayTestExecutionListener.locationsMigrationHandling(FlywayTestExecutionListener.java:444)
	at org.flywaydb.test.FlywayTestExecutionListener.dbResetWithAnnotation(FlywayTestExecutionListener.java:399)
```

**Comment by FlorianGWE** [comment]
Ok the missing is to support Flyway 5.1 instead of support for Spring 5.1. 
Flyway 5.1 brings breaking changes see https://flywaydb.org/documentation/releaseNotes issue 1707 and issue 1928

**Comment by YashchenkoN** [comment]
@FlorianGWE so new version of the test extension should handle breaking changes

**Comment by FlorianGWE** [comment]
pushed to sonatype and released.
waiting for promotion to maven central
